/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/v1/auth/google': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Entra com o ID token do Google Sign-In (cria a conta no primeiro acesso). */
    post: operations['AuthController_entrarComGoogle'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/auth/codigo': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Envia um código de 6 dígitos para o e-mail. A resposta é a mesma exista ou não a conta. */
    post: operations['AuthController_pedirCodigo'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/auth/codigo/verificar': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Entra com o código recebido por e-mail (cria a conta no primeiro acesso). */
    post: operations['AuthController_entrarComCodigo'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/auth/senha': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** E-mail e senha: só para a conta de demonstração do revisor da loja. */
    post: operations['AuthController_entrarComSenha'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/auth/renovar': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Troca o refresh token por um novo par de tokens (o refresh antigo deixa de valer). */
    post: operations['AuthController_renovar'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/auth/sair': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Encerra a sessão deste refresh token. */
    post: operations['AuthController_sair'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Dados da conta logada e do perfil (`perfil: null` enquanto o cadastro não for concluído). */
    get: operations['MeController_obter'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/me/cadastro': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Conclui o cadastro: apelido público, declaração de 18 anos e aceite dos termos. */
    post: operations['MeController_concluirCadastro'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/casinhas': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Casinhas da área visível do mapa (no máximo 1.000). A coordenada é a exata só para quem
     *     pode vê-la (criador, adotante, moderador e o verificado nas que já abriu hoje).
     */
    get: operations['CasinhasController_listarNaArea'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/casinhas/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Detalhe da casinha. Para o verificado, ver a exata gasta 1 das 50 casinhas do dia. */
    get: operations['CasinhasController_detalhe'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/me/casinhas': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Casinhas que criei ou adoto, com status e localização exata. */
    get: operations['MinhasCasinhasController_listar'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/necessidades': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Reporta o que falta. Se o tipo já está aberto, vira "ainda precisa" (RN02). */
    post: operations['NecessidadesController_reportar'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/necessidades/{id}/reconfirmar': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** "Ainda precisa": renova o prazo. 1 vez a cada 12 h por usuário. */
    post: operations['NecessidadesController_reconfirmar'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/necessidades/{id}/atender': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** "Abasteci" / "Atendi". Se alguém resolveu antes, devolve `ja_atendida` (RN03). */
    post: operations['NecessidadesController_atender'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/necessidades/{id}/contestar': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** "Não foi resolvido": reabre até 24 h depois do atendimento (RN03). */
    post: operations['NecessidadesController_contestar'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/casinhas/{id}/check-in': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** "Passei aqui, tudo ok". */
    post: operations['NecessidadesController_checkIn'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/saude': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Verifica se a API e o banco estão no ar (usado pelo monitoramento e pelo deploy). */
    get: operations['SaudeController_verificar'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    EntrarComGoogleDto: {
      /** @description ID token devolvido pelo Google Sign-In no app. */
      idToken: string;
    };
    TokensResposta: {
      /** @description JWT de acesso: enviar em `Authorization: Bearer <acesso>`. */
      acesso: string;
      /** Format: date-time */
      acessoExpiraEm: string;
      /** @description Token para renovar a sessão em `POST /v1/auth/renovar`. Guardar em armazenamento seguro. */
      refresh: string;
      /** Format: date-time */
      refreshExpiraEm: string;
      /** @description `true` enquanto o usuário não concluir o cadastro (apelido, 18 anos, termos). */
      precisaCadastro: boolean;
    };
    PedirCodigoDto: {
      /** Format: email */
      email: string;
    };
    VerificarCodigoDto: {
      /** Format: email */
      email: string;
      /** @description Código de 6 dígitos recebido por e-mail. */
      codigo: string;
    };
    EntrarComSenhaDto: {
      /** Format: email */
      email: string;
      senha: string;
    };
    RefreshDto: {
      refresh: string;
    };
    PerfilResposta: {
      apelido: string;
      /** @enum {string} */
      nivel: 'colaborador' | 'verificado' | 'moderador' | 'admin';
      /** Format: date-time */
      bloqueadoAte: string | null;
    };
    MeResposta: {
      id: string;
      email: string;
      /** @description `null` enquanto o cadastro não for concluído. */
      perfil: components['schemas']['PerfilResposta'] | null;
    };
    ConcluirCadastroDto: {
      /**
       * @description Nome público, de 3 a 30 caracteres: letras, números, espaço, `_`, `.` e `-`.
       *     Não pode parecer e-mail nem telefone (8 ou mais dígitos seguidos).
       */
      apelido: string;
      /** @description Declaração de que o usuário tem 18 anos ou mais. */
      maiorDeIdade: boolean;
      /** @description Versão dos termos que o usuário aceitou (tem que ser a vigente). */
      termosVersao: string;
    };
    CasinhaNoMapa: {
      id: string;
      nome: string;
      /** @enum {string} */
      status: 'ok' | 'atencao' | 'urgente' | 'sem_noticias';
      /** @enum {string} */
      animais: 'caes' | 'gatos' | 'ambos';
      /** @description Exata se `exata = true`; senão, a pública (desenhar como área de 500 m, nunca como pino). */
      lat: number;
      lng: number;
      exata: boolean;
      /** @description Tipos das necessidades abertas (filtros e ícones do mapa). */
      necessidadesAbertas: (
        'racao' | 'agua' | 'reforma' | 'cobertas' | 'limpeza' | 'remedio_veterinario' | 'outro'
      )[];
    };
    CasinhasNaAreaResposta: {
      casinhas: components['schemas']['CasinhaNoMapa'][];
      /** @description `true` se a área tinha mais de 1.000 casinhas e só as 1.000 primeiras vieram: aproxime o mapa. */
      truncado: boolean;
    };
    NecessidadeAberta: {
      id: string;
      /** @enum {string} */
      tipo: 'racao' | 'agua' | 'reforma' | 'cobertas' | 'limpeza' | 'remedio_veterinario' | 'outro';
      /** @enum {string} */
      urgencia: 'urgente' | 'normal';
      observacao: string | null;
      /** Format: date-time */
      criadaEm: string;
      /** Format: date-time */
      expiraEm: string;
    };
    AtendidaRecentemente: {
      id: string;
      /** @enum {string} */
      tipo: 'racao' | 'agua' | 'reforma' | 'cobertas' | 'limpeza' | 'remedio_veterinario' | 'outro';
      /** Format: date-time */
      atendidaEm: string;
      /** @description Quem atendeu (`null` = conta excluída). */
      apelido: string | null;
    };
    AtividadeResumo: {
      id: string;
      /** @enum {string} */
      tipo:
        | 'cadastro'
        | 'reporte'
        | 'reconfirmacao'
        | 'atendimento'
        | 'contestacao'
        | 'check_in'
        | 'edicao'
        | 'adocao'
        | 'fim_adocao'
        | 'expiracao'
        | 'desativacao_pedida'
        | 'moderacao';
      /**
       * @description Tipo da necessidade envolvida (reporte, atendimento etc.), para o texto "abasteceu ração".
       * @enum {string|null}
       */
      necessidade:
        | 'racao'
        | 'agua'
        | 'reforma'
        | 'cobertas'
        | 'limpeza'
        | 'remedio_veterinario'
        | 'outro'
        | null;
      /** @description `null` quando a conta foi excluída (mostrar "Usuário removido"). */
      apelido: string | null;
      observacao: string | null;
      /** Format: date-time */
      criadaEm: string;
    };
    MinhasPermissoes: {
      editar: boolean;
      /** @description Ainda sujeito, na hora de adotar, à distância de até 100 m (exceto para o criador). */
      adotar: boolean;
      deixarDeAdotar: boolean;
      pedirDesativacao: boolean;
      desativar: boolean;
      denunciar: boolean;
    };
    CasinhaDetalhe: {
      id: string;
      nome: string;
      descricao: string | null;
      /** @enum {string} */
      animais: 'caes' | 'gatos' | 'ambos';
      /** @enum {string} */
      status: 'ok' | 'atencao' | 'urgente' | 'sem_noticias';
      /** @description Exata se `exata = true`; senão, a pública. "Como chegar" só com `exata = true`. */
      lat: number;
      lng: number;
      exata: boolean;
      /** Format: date-time */
      ultimaAtividadeEm: string;
      /** Format: date-time */
      criadaEm: string;
      necessidadesAbertas: components['schemas']['NecessidadeAberta'][];
      /** @description Resolvidas nas últimas 24 h, para o botão "Não foi resolvido". */
      atendidasRecentemente: components['schemas']['AtendidaRecentemente'][];
      /** @description Apelidos dos adotantes ativos. */
      adotantes: string[];
      /** @description As 30 mais recentes, da mais nova para a mais antiga. */
      atividades: components['schemas']['AtividadeResumo'][];
      minhasPermissoes: components['schemas']['MinhasPermissoes'];
    };
    MinhaCasinha: {
      id: string;
      nome: string;
      /** @enum {string} */
      status: 'ok' | 'atencao' | 'urgente' | 'sem_noticias';
      /** @enum {string} */
      animais: 'caes' | 'gatos' | 'ambos';
      /** @description Exata se `exata = true`; senão, a pública (desenhar como área de 500 m, nunca como pino). */
      lat: number;
      lng: number;
      exata: boolean;
      /** @description Tipos das necessidades abertas (filtros e ícones do mapa). */
      necessidadesAbertas: (
        'racao' | 'agua' | 'reforma' | 'cobertas' | 'limpeza' | 'remedio_veterinario' | 'outro'
      )[];
      souCriador: boolean;
      souAdotante: boolean;
    };
    ReportarNecessidadeDto: {
      /**
       * Format: uuid
       * @description Gerado no celular. Reenviar o mesmo id não duplica nada (idempotência).
       */
      id: string;
      /** Format: uuid */
      casinhaId: string;
      /** @enum {string} */
      tipo: 'racao' | 'agua' | 'reforma' | 'cobertas' | 'limpeza' | 'remedio_veterinario' | 'outro';
      /** @enum {string} */
      urgencia: 'normal' | 'urgente';
      observacao?: string;
      lat?: number;
      lng?: number;
      /**
       * Format: date-time
       * @description Quando a ação foi feita no celular (pode ser bem antes do envio, se estava offline).
       */
      criadaNoCelularEm?: string;
    };
    ResultadoAcao: {
      /**
       * @description - `ok`: feito.
       *     - `reconfirmada`: o tipo já estava aberto; o reporte virou "ainda precisa" (e a urgência subiu, se for o caso).
       *     - `ja_reconfirmada`: você já tinha confirmado nas últimas 12 h; nada mudou.
       *     - `ja_atendida`: alguém resolveu antes; o seu atendimento ficou só no histórico. Mostre "Alguém já tinha atendido. Obrigado!".
       * @enum {string}
       */
      resultado: 'ok' | 'reconfirmada' | 'ja_reconfirmada' | 'ja_atendida';
      /** @description Necessidade afetada (no reporte que virou reconfirmação, a que já estava aberta). */
      necessidadeId: string | null;
      /**
       * @description Status da casinha depois da ação.
       * @enum {string}
       */
      status: 'urgente' | 'ok' | 'atencao' | 'sem_noticias';
    };
    AcaoDto: {
      /**
       * Format: uuid
       * @description Gerado no celular: id da atividade no histórico e chave de idempotência.
       */
      atividadeId: string;
      lat?: number;
      lng?: number;
      /**
       * Format: date-time
       * @description Quando a ação foi feita no celular (pode ser bem antes do envio, se estava offline).
       */
      criadaNoCelularEm?: string;
    };
    AtenderDto: {
      /**
       * Format: uuid
       * @description Gerado no celular: id da atividade no histórico e chave de idempotência.
       */
      atividadeId: string;
      lat?: number;
      lng?: number;
      /**
       * Format: date-time
       * @description Quando a ação foi feita no celular (pode ser bem antes do envio, se estava offline).
       */
      criadaNoCelularEm?: string;
      observacao?: string;
    };
    ContestarDto: {
      /** Format: uuid */
      atividadeId: string;
      /** @description O que não foi feito (ex.: "o pote continua vazio"). */
      observacao: string;
    };
    SaudeResposta: {
      /** @description `true` quando a API e o banco estão respondendo. */
      ok: boolean;
      /**
       * @description Estado da conexão com o Postgres.
       * @enum {string}
       */
      banco: 'ok' | 'erro';
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  AuthController_entrarComGoogle: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['EntrarComGoogleDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TokensResposta'];
        };
      };
    };
  };
  AuthController_pedirCodigo: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['PedirCodigoDto'];
      };
    };
    responses: {
      202: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthController_entrarComCodigo: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['VerificarCodigoDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TokensResposta'];
        };
      };
    };
  };
  AuthController_entrarComSenha: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['EntrarComSenhaDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TokensResposta'];
        };
      };
    };
  };
  AuthController_renovar: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RefreshDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TokensResposta'];
        };
      };
    };
  };
  AuthController_sair: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RefreshDto'];
      };
    };
    responses: {
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  MeController_obter: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MeResposta'];
        };
      };
    };
  };
  MeController_concluirCadastro: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ConcluirCadastroDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PerfilResposta'];
        };
      };
    };
  };
  CasinhasController_listarNaArea: {
    parameters: {
      query: {
        minLat: number;
        minLng: number;
        maxLat: number;
        maxLng: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CasinhasNaAreaResposta'];
        };
      };
    };
  };
  CasinhasController_detalhe: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CasinhaDetalhe'];
        };
      };
    };
  };
  MinhasCasinhasController_listar: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MinhaCasinha'][];
        };
      };
    };
  };
  NecessidadesController_reportar: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ReportarNecessidadeDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ResultadoAcao'];
        };
      };
    };
  };
  NecessidadesController_reconfirmar: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AcaoDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ResultadoAcao'];
        };
      };
    };
  };
  NecessidadesController_atender: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AtenderDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ResultadoAcao'];
        };
      };
    };
  };
  NecessidadesController_contestar: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ContestarDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ResultadoAcao'];
        };
      };
    };
  };
  NecessidadesController_checkIn: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AcaoDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ResultadoAcao'];
        };
      };
    };
  };
  SaudeController_verificar: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SaudeResposta'];
        };
      };
      /** @description Banco indisponível */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}
